INSERT INTO lists (listtype, id, created, title, description, due, priority, status) VALUES ('Projectlist',1, '2023-08-02', 'Gute Liste', 'Dies ist ein Beispiel', '2023-02-18', 1, 1)
INSERT INTO lists (listtype, id, created, title, description, due, priority, status) VALUES ('Projectlist',3, '2023-10-02', 'Gute abgeschlossene Liste', 'Dies ist ein zweites Beispiel', '2023-02-18', 1, 1)
INSERT INTO lists (listtype, id, created, title, description, due, priority, status) VALUES ('Projectlist',4, '2023-10-02', 'Gute zweite Liste', 'Dies ist ein drittes Beispiel, das bleibt', '2023-02-18', 1, 1)
INSERT INTO task (id, created, description, due_date, status, title, lists_id) VALUES (1, '2023-02-08','Viele Aufgaben', '2023-02-12',1, 'FSWD', 1)
INSERT INTO lists_task_list (lists_id, task_list_id) VALUES (1,1)
INSERT INTO lists (listtype, id, created, title, icon_name) VALUES ('Actionlist',2, '2023-08-02', 'Aktionsliste', 'card')
INSERT INTO task (id, created, description, due_date, status, title, lists_id) VALUES (2, '2023-02-08','Viele Aufgaben', '2023-02-12',1, 'Aktionslisteaufgabe', 2)
INSERT INTO lists_task_list (lists_id, task_list_id) VALUES (2,2)